export const enterprisesConstant = {
  ENTERPRISE_REQUEST: 'ENTERPRISE_REQUEST',
  ENTERPRISES_SET: 'ENTERPRISES_SET',
  ENTERPRISES_FILTER_REQUEST: 'ENTERPRISES_FILTER_REQUEST',
  ENTERPRISES_FILTER_SET: 'ENTERPRISES_FILTER_SET',
  ENTERPRISES_DETAILS_REQUEST: 'ENTERPRISES_DETAILS_REQUEST',
  ENTERPRISES_DETAILS_SET: 'ENTERPRISES_DETAILS_SET',
  ENTERPRISES_FILTER_CLEAR: 'ENTERPRISES_FILTER_CLEAR',
};